cabal-version:      3.0
name:               boa
version:            0.1.0.0

license:            MIT
author:             Student
maintainer:         foo@uio.no

category:           Language
build-type:         Simple

common dependencies
  build-depends:
      base >=4.18.1.0,
      parsec ^>=3.1.18.0

common testing-tools
  build-depends:
      tasty
    , tasty-hunit
    , tasty-quickcheck

library
    import:           dependencies
    exposed-modules:  Syntax Interpreter Parser
    hs-source-dirs:   src
    default-language: Haskell2010

executable boa
    import:           dependencies
    build-depends:    boa
    main-is:          Driver.hs
    hs-source-dirs:   app
    default-language: Haskell2010

test-suite boa-test
    import:           dependencies
    import:           testing-tools
    build-depends:    process ^>=1.6.26.1, containers ^>=0.8, boa, QuickCheck ^>=2.18.0.0
    default-language: Haskell2010
    type:             exitcode-stdio-1.0
    hs-source-dirs:   tests
    main-is:          Test.hs
    other-modules:    InterpreterTests, ParserTests, Gen.BoaProgram
